version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: touhou_arrangement_chronicle
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: "./docker/psqldef/Dockerfile"
    volumes:
      - ./db:/app/db
    working_dir: /app
    command:
      - "./psqldef"
      - "--file"
      - "./db/schema/schema.sql"
      - "--host"
      - "db"
      - "touhou_arrangement_chronicle"
    depends_on:
      - db
    profiles:
      - extra

  server:
    build:
      context: .
      dockerfile: "./docker/server/Dockerfile"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      CONNECT_URL: "postgres://postgres:@db:5432/touhou_arrangement_chronicle?sslmode=disable"
    volumes:
      - .:/app

volumes:
  postgres:
